version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080